### ISSUE TITLE
BindException: Address already in use: Cannot bind

### ISSUE THREAD

**Issue by kozmoz** [kozmoz/atag-one-api#30]
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) Client VM (build 25.191-b12, mixed mode)

`Input Output Error: java.net.BindException: Address already in use:
Cannot bind
java.net.BindException: Address already in use: Cannot bind
at java.net.DualStackPlainDatagramSocketImpl.socketBind(Native
Method)
at java.net.DualStackPlainDatagramSocketImpl.bind0(Unknown Source)
at java.net.AbstractPlainDatagramSocketImpl.bind(Unknown Source)
at java.net.DatagramSocket.bind(Unknown Source)
at java.net.DatagramSocket.(Unknown Source)
at java.net.DatagramSocket.(Unknown Source)
at
org.juurlink.atagone.utils.NetworkUtils.getUdpBroadcastMessage(NetworkUtils.java:337)
at
org.juurlink.atagone.AtagOneLocalConnector.searchOnes(AtagOneLocalConnector.java:457)
at
org.juurlink.atagone.AtagOneLocalConnector.login(AtagOneLocalConnector.java:152)
at org.juurlink.atagone.AtagOneApp.main(AtagOneApp.java:88)`

**Comment by kozmoz** [comment]
The program creates a socket and tries to connect it to IP 0.0.0.0.

For now, omit the IP address to bind to and let Java figure out which local network address to connect to. (by omitting it as parameter to the bind call).
