### ISSUE TITLE
java problem on iMac (running OSX 10.13.6)

### ISSUE THREAD

**Issue by softpol** [kozmoz/atag-one-api#33]
[iMac-C4:~] pol% java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

[iMac-C4:~/Downloads] pol% java -jar atag-one.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/juurlink/atagone/AtagOneApp : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by kozmoz** [comment]
Version 1.4.1 was the latest version that supports Java 6. Newer versions need at least Java 8 and cannot be compiled for Java 6 anymore. The issue cannot and will not be fixed.

See the releases page to download a Java 6 compatible version: https://github.com/kozmoz/atag-one-api/releases
